export enum PermissionsAllowedTypes {
    CREATE_OFFER = 'CREATE_OFFER',
    CREATE_QUOTATION = 'CREATE_QUOTATION',
    REFUSE_OFFER = 'REFUSE_OFFER',
    SET_WINNER_OFFER = 'SET_WINNER_OFFER',
    GET_COMPANY_CLIENTS = 'GET_COMPANY_CLIENTS',
    GET_OFFERS = 'GET_OFFERS',
    GET_OFFER = 'GET_OFFER',
    GET_QUOTATIONS = 'GET_QUOTATIONS',
    GET_QUOTATION = 'GET_QUOTATION',
    SEND_QUOTATION_CREATION_EMAIL = 'SEND_QUOTATION_CREATION_EMAIL',
    COMPANY_GROUP = 'COMPANY_GROUP'
}
