import { MakeEnviroment } from './interfaces/make-enviroment.interface';

export const makeEnviroment = (
  ENV_LOGIN: string,
  ENV_PATH: string,
  ENV_BACKOFFICE: string,
  production: boolean,
  tagManager: string,
  ambiente: string,
  ENV_BUCKET_CREATE_QUOTATION: string,
  ENV_BUCKET_AUTH: string,
  ENV_BUCKET_HIRING_PROPOSAL: string
): MakeEnviroment => ({
  version: '1.0.29',
  production,
  ambiente,
  ENV_PATH,
  TAG_MANAGER: tagManager,
  QUOTATION: `${ENV_PATH}/quotation/`,
  QUOTATIONS: `${ENV_PATH}/quotations/`,
  OFFER: `${ENV_PATH}/offer`,
  REFUSE_OFFER: `${ENV_PATH}/refuse_offer/`,
  LOGIN: `${ENV_LOGIN}/login/`,
  CLIENTS: `${ENV_PATH}/clients/`,
  CLIENT: `${ENV_PATH}/client`,
  COMPANY_GROUPS: `${ENV_PATH}/company_groups/`,
  COMPANY_GROUP: `${ENV_PATH}/company_group/`,
  COMPANY: `${ENV_PATH}/company`,
  AGENTS: `${ENV_PATH}/agents/`,
  BACKOFFICE: `${ENV_BACKOFFICE}`,
  BILLING_INFO: `${ENV_PATH}/billing_info`,
  USER: `${ENV_PATH}/user/`,
  USERS: `${ENV_PATH}/users/`,
  DEFAULT_DATE: `${ENV_PATH}/systems/default_date`,
  ENV_BUCKET_CREATE_QUOTATION,
  ENV_BUCKET_AUTH,
  ENV_BUCKET_HIRING_PROPOSAL,
});
