import { BillingInfo } from './billing-info.interface';
import { FinancialGuarantee } from './financial-guarantee.interface';

export interface Offer {
  revisionObservation?: any;
  formattedPaymentBusinessDay: string;
  energyVolumeHour: string;
  changed: boolean;
  status: string;
  retusd: number;
  sourceOffer?: any;
  createdAt: Date;
  observation?: any;
  energyVolumeAverage: string;
  id: string;
  formattedPeriod: string;
  paymentBusinessDay: number;
  price: number;
  offerType: string;
  billingInfo: BillingInfo | string;
  ownerId: string;
  paymentDayType: string;
  email?: any;
  formattedEnergyVolumeHour: string;
  formattedEnergyVolumeAverage: string;
  fullReparation: boolean;
  proposalExpiration: Date;
  fantasyName?: string;
  registrationForm?: string;
  companyName?: string;
  offererName?: string;
  quotationId?: string;
  indexer?: string;
  minimumSeasonality?: number;
  maximumSeasonality?: number;
  minimumFlexibility?: number;
  maximumFlexibility?: number;
  minimalModulation?: number;
  maximumModulation?: number;
  modulationType?: string;
  financialGuarantee?: string[] | FinancialGuarantee[];
}
