import { FinancialGuarantee } from './financial-guarantee.interface';
import { Owner } from './owner.interface';
import { QuotationFile } from './quotation-file.interface';

export interface Quotation {
  retusd?: number;
  priceType: string;
  ownerId: string[];
  energySource: string;
  id?: string;
  status?: string;
  protocol?: string;
  quotationType: string;
  subMarketRegion: string;
  startDate: string;
  countOffers?: number;
  paymentBusinessDay: string;
  endDate: string;
  proposalSubmission: string;
  energyVolumeAverage: string;
  expiration: string;
  observation: string;
  companyGroups?: string[];
  sendEmailWithPrice?: boolean;
  timer?: string;
  energyVolumeHour?: string;
  formattedPaymentBusinessDay?: string;
  formattedEnergyVolumeHour?: string;
  formattedEnergyVolumeAverage?: string;
  fantasyName?: string;
  owner?: Owner[];
  billingInfo: string;
  countOffersWinners: number;
  indexer?: string;
  fullReparation?: boolean;
  files?: QuotationFile[];
  proposalTimeRemaining?: number;
  proposalTolerance?: string;
  paymentDayType?: string;
  minimumSeasonality?: number;
  maximumSeasonality?: number;
  minimumFlexibility?: number;
  maximumFlexibility?: number;
  minimalModulation?: number;
  maximumModulation?: number;
  modulationType?: string;
  financialGuarantee?: string[] | FinancialGuarantee[];
  isLongTerm?: boolean;
  proposalTimeRemainingWithoutTolerance?: number;
}
